version: '3.8'
services:
  user-prod:
    image: ghcr.io/nervus-tech/nervus-user:v1.1.0-prod
    container_name: user-prod
    ports:
      - "8107:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - HIBERNATE_DEFAULT_SCHEMA=prod_users
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
    networks:
      - nervus-infrastructure_default
    # depends_on removed - using shared infrastructure
  # PostgreSQL service removed - using shared infrastructure

networks:
  nervus-infrastructure_default:
    external: true 