version: '3.8'
services:
  staging:
    image: ghcr.io/nervus-tech/nervus-user:v1.0.0
    ports:
      - "8106:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=staging_users
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    # depends_on removed - using shared infrastructure
  # PostgreSQL service removed - using shared infrastructure 